### PR TITLE
Added UI

### PR DESCRIPTION
**Pull request by Sumit4482**

### CODE REVIEW

**Review by naveeramesh — CHANGES_REQUESTED** [review]
Try to give different names instead of "Username",
Change the time , it should varies for every users
Add image to the User
Btw good job, Try to make these changes and Update.

**Comment by Sumit4482** [comment]
@naveeramesh Sure,
I will make these changes.

**Comment by Sumit4482** [comment]
@naveeramesh  I have made the required changes .

**Comment by naveeramesh** [comment]
@Sumit4482 output screenshot pls.

**Comment by Sumit4482** [comment]
@naveeramesh Done !! Added Screenshot.

**Comment by naveeramesh** [comment]
@naveeramesh awesome work

**Pull request merged**
