### PR TITLE
Music Player App Song Playing Screen

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Created Song Playing Screen with preview at bottom in which current playing song is shown.
- On clicking on the bottom where music is playing will lead to music playing screen.
-  Flutter animation is used
- Duration of song is varied each second to give a touch like song is actually playing in UI.
- Related to issue #50 

- At the bottom one of the song is playing as we can see.

-  Now the duration of the playing song is varied and we scroll down to check if free from overflow

- Now clicking on the bottom to go to playing screen

- Going back and checking if other songs too working.

- Clicking on it too to make sure if it is also working and going to playing screen

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech  @naveeramesh  kindly approve this pr thanks

**Comment by naveeramesh** [comment]
@Jaideep25-tech great to merge

**Review by naveeramesh — APPROVED** [review]
Great work, keep contributing and inspiring

**Comment by mdnazisharman2803** [comment]
> Great work, keep contributing and inspiring

Thank you mam

**Review by Jaideep25-tech — APPROVED** [review]

**Comment by mdnazisharman2803** [comment]
@naveeramesh  @Jaideep25-tech  can u please add this label 3  . I guess this pr deserves it. I have added much functionality, I think just one screen pr should get label 2 but I've added multiple Features

**Comment by mdnazisharman2803** [comment]
@naveeramesh  please add level 3 to this pr mam

**Pull request merged**
