### PR TITLE
Car booking details screen

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Created Car booking details Screen.
- Added feature to book car and call owner.
- For the issue #102 
- Here is the output below:

Screenshot (741)

- Going back and check if other car details loaded.
Screenshot (740)

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@naveeramesh  @Jaideep25-tech  kindly approve this pr .

**Comment by naveeramesh** [comment]
This issue was created by you right so I guess this won't be counted right?

**Comment by mdnazisharman2803** [comment]
> This issue was created by you right so I guess this won't be counted right?

The announcement was that after 6 pm not to make any new issue or not work on any assigned one... 

But this apo have just last screen left so I just created pr so that the app not left incomplete.. Kindly approce this mam

**Review by naveeramesh — APPROVED** [review]

**Comment by naveeramesh** [comment]
@Jaideep25-tech you can merge them if this comes under consideration I have approved the code work

**Comment by mdnazisharman2803** [comment]
@naveeramesh mam  can you add labels to thi pr ,

**Review by Jaideep25-tech — APPROVED** [review]

**Pull request merged**
