### PR TITLE
Made login screen

### LINKED ISSUE #5: Login Screen
Create a simple Login Screen with minimalistic components.
Follow the Guidelines and code of conduct.
Check the [Login Folder](https://github.com/Dezenix/native-frontend-flutter/tree/main/Login_Screens/Login01) once.

### PR DESCRIPTION
**Pull request by sanjanarp**
Closes #5 
Made a log in screen for the app. Added an animation to the logo and added input fields to username and password using which users can log in. Forgot password and Register buttons are also added in the log in screen

@naveeramesh Any changes required?

### CODE REVIEW

**Comment by naveeramesh** [comment]
@sanjanarp will review shortly but do follow the guidelines for the commit message .

**Review by naveeramesh — CHANGES_REQUESTED** [review]
Create a new branch with the format Your Name Issue Name and follow the [Guidelines](https://github.com/Dezenix/native-frontend-flutter/blob/main/Guidelines.md),also attach the output screenshot.

**Comment by sanjanarp** [comment]
Do I delete this pull request and make a new one?

**Comment by naveeramesh** [comment]
> Do I delete this pull request and make a new one?

If you wish to delete and make a new one you can else go with doing changes for this same pr.

**Comment by sanjanarp** [comment]
image
I'm unsure of which of these commit messages I should use

**Comment by naveeramesh** [comment]
> image @naveeramesh I'm unsure of which of these commit messages I should use

@sanjanarp use feat : followed by the commit message when you change any code / when you create any new file / modifying existing code.
fix: follwed by commit message when you remove soma images or code or any kinda spaces

**Pull request closed without merging**
