### PR TITLE
add login screen for diet app

### PR DESCRIPTION
**Pull request by chinmayilondhe**

### CODE REVIEW

**Comment by naveeramesh** [comment]
Attach the screen shot

**Comment by chinmayilondhe** [comment]
yes,I've added it. Please check.

**Comment by naveeramesh** [comment]
Next time try to add over the pr itself.
@Jaideep25-tech good to go you can merge them

**Review by naveeramesh — APPROVED** [review]

**Comment by chinmayilondhe** [comment]
Yes, Will keep in mind. Thank you.

**Pull request merged**
