### PR TITLE
home screen

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
done

### CODE REVIEW

**Comment by naveeramesh** [comment]
Attach the output screenshot and mention your issue number

**Comment by mdnazisharman2803** [comment]
Okk I'll do it soon as exams going on till 9th of april🙂

**Comment by naveeramesh** [comment]
> Okk I'll do it soon as exams going on till 9th of april

**Comment by naveeramesh** [comment]
> > Okk I'll do it soon as exams going on till 9th of april

Do asap

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech  sir  according to girl script label should be

GSSoC22
Level2

Please update both label please sir thank you

**Pull request merged**
