### PR TITLE
Sign In Screen of Exercise App

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Created Completely Responsive Sing up Screen using provider.
- For the issue #78 
- Here is the output below:

Screenshot (538)

- Opening keyboard to make sure if everything is smooth , here is the output below

Screenshot (539)

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@naveeramesh kindly approve this pr thanks

**Review by naveeramesh — APPROVED** [review]

**Comment by mdnazisharman2803** [comment]
> @mdnazisharman2803 good work keep it up. @Jaideep25-tech good to merge

thanks mam

**Comment by mdnazisharman2803** [comment]
@naveeramesh  any update when it's going to be merge🥺🥺 it's demoralizing.. My last pr even merged I didn't get any points because of wrong label.. It's also waiting in row 😢😢 it seriously affecting me on leaderboard

**Comment by naveeramesh** [comment]
@mdnazisharman2803 merge part was by @Jaideep25-tech I had already informed him to merge

**Comment by naveeramesh** [comment]
@Jaideep25-tech merge asap

**Comment by mdnazisharman2803** [comment]
Okk mam

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech  @naveeramesh  can you add label here? No label..

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech  please add GSSoC lab

**Pull request merged**
