### PR TITLE
Interest Selection Screen

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Created Interest selection screen with different choices of exercises.
- For the issue #78 
- Here is the output below:

- A list of choices of exercise with duration to be done is given.

Screenshot (587)

- Scrolling to make sure if its fine and checking if free of overflow.

Screenshot (588)

Screenshot (589)

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech @naveeramesh  please approve this pr kindly thank you

**Comment by naveeramesh** [comment]
@Jaideep25-tech good to merge

**Review by naveeramesh — APPROVED** [review]

**Comment by mdnazisharman2803** [comment]
@naveeramesh  thank you mam

**Comment by mdnazisharman2803** [comment]
@Jaideep25-tech  please add GSSoC22 label and level label please

**Pull request merged**
