### PR TITLE
Neumorphism Music Player Navigated Drawer and Settings Screen

### PR DESCRIPTION
**Pull request by mdnazisharman2803**
- Created Navigated Drawer also designed settings Screen in Neumorphism Music Player app.
- For the issue #55  
- Here is the output below:

- Drawer with special effect and different items.

- Settings screen

- Scrolling down to check if everything is fine

### CODE REVIEW

**Comment by mdnazisharman2803** [comment]
@naveeramesh @Jaideep25-tech  kindly approve this pr thanks

**Comment by naveeramesh** [comment]
@mdnazisharman2803 you can change the color combination to green something similar to Spotify.

**Review by naveeramesh — CHANGES_REQUESTED** [review]
You can change the color combination to green something similar to Spotify.

**Comment by mdnazisharman2803** [comment]
> You can change the color combination to green something similar to Spotify.

Mam.. Actually the original app which isn't made by me is having this color , so to maintain Homoginty in the color combination I've used the existing color as it will look odd if I use green because rest of the placed whole app is made in dark sky blue color even the list screen as well as details screen.

**Review by naveeramesh — APPROVED** [review]

**Comment by naveeramesh** [comment]
@Jaideep25-tech you can merge now.

**Review by Jaideep25-tech — APPROVED** [review]

**Pull request merged**
